-- ============================================================
-- Phase 9: Monitoring & Cost Control
-- ============================================================

-- Resource Monitor (spending limits)
CREATE OR REPLACE RESOURCE MONITOR DAILY_CREDIT_MONITOR
  WITH CREDIT_QUOTA = 10 FREQUENCY = DAILY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE PIPELINE_WH SET RESOURCE_MONITOR = DAILY_CREDIT_MONITOR;

-- Cost Monitoring View
CREATE OR REPLACE VIEW SALES_DW.ANALYTICS.V_COST_MONITOR AS
SELECT
    DATE_TRUNC('day', START_TIME) AS USAGE_DATE,
    WAREHOUSE_NAME,
    ROUND(SUM(CREDITS_USED), 4) AS DAILY_CREDITS,
    ROUND(SUM(CREDITS_USED) * 3.00, 2) AS ESTIMATED_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY 1, 2 ORDER BY 1 DESC, 4 DESC;

-- Credit usage by warehouse (last 30 days)
SELECT WAREHOUSE_NAME, ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS,
       COUNT(*) AS USAGE_RECORDS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME ORDER BY TOTAL_CREDITS DESC;

-- Top 10 most expensive queries (last 7 days)
SELECT QUERY_ID, USER_NAME, WAREHOUSE_NAME, QUERY_TYPE,
       ROUND(TOTAL_ELAPSED_TIME / 1000, 2) AS ELAPSED_SECONDS,
       ROWS_PRODUCED, SUBSTR(QUERY_TEXT, 1, 80) AS QUERY_PREVIEW
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP()) AND WAREHOUSE_NAME IS NOT NULL
ORDER BY TOTAL_ELAPSED_TIME DESC LIMIT 10;

-- Storage usage by database
SELECT DATABASE_NAME,
       ROUND(AVERAGE_DATABASE_BYTES / POWER(1024, 3), 4) AS AVG_STORAGE_GB,
       ROUND(AVERAGE_FAILSAFE_BYTES / POWER(1024, 3), 4) AS FAILSAFE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE = CURRENT_DATE() - 1
ORDER BY AVG_STORAGE_GB DESC;

-- Failed queries (last 24h)
SELECT QUERY_ID, ERROR_MESSAGE, SUBSTR(QUERY_TEXT, 1, 100) AS QUERY_PREVIEW
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE EXECUTION_STATUS = 'FAIL' AND START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC LIMIT 20;

-- Resource monitor status
SHOW RESOURCE MONITORS;
