-- ============================================================
-- Phase 6: Data Sharing — Secure Views & Shares
-- ============================================================

-- Secure Views (hide SQL logic from consumers)
CREATE OR REPLACE SECURE VIEW SALES_DW.ANALYTICS.SHARED_CUSTOMER_SUMMARY AS
SELECT
    SEGMENT, COUNTRY,
    COUNT(*) AS CUSTOMER_COUNT,
    SUM(TOTAL_ORDERS) AS TOTAL_ORDERS,
    SUM(LIFETIME_REVENUE) AS TOTAL_REVENUE,
    AVG(AVG_ORDER_VALUE) AS AVG_ORDER_VALUE
FROM SALES_DW.ANALYTICS.DIM_CUSTOMERS
GROUP BY SEGMENT, COUNTRY;

CREATE OR REPLACE SECURE VIEW SALES_DW.ANALYTICS.SHARED_DAILY_SALES AS
SELECT ORDER_DATE, ORDER_COUNT, DAILY_REVENUE, AVG_ORDER_VALUE, TOTAL_ITEMS_SOLD
FROM SALES_DW.ANALYTICS.DAILY_SALES_SUMMARY;

-- Create Share
CREATE OR REPLACE SHARE SALES_ANALYTICS_SHARE
  COMMENT = 'Shared sales analytics - aggregated metrics only, no PII';

-- Grant access to share
GRANT USAGE ON DATABASE SALES_DW TO SHARE SALES_ANALYTICS_SHARE;
GRANT USAGE ON SCHEMA SALES_DW.ANALYTICS TO SHARE SALES_ANALYTICS_SHARE;
GRANT SELECT ON VIEW SALES_DW.ANALYTICS.SHARED_CUSTOMER_SUMMARY TO SHARE SALES_ANALYTICS_SHARE;
GRANT SELECT ON VIEW SALES_DW.ANALYTICS.SHARED_DAILY_SALES TO SHARE SALES_ANALYTICS_SHARE;

-- Add consumer account (replace with actual account)
-- ALTER SHARE SALES_ANALYTICS_SHARE ADD ACCOUNTS = <consumer_account>;

-- Consumer side (run in consumer account):
-- CREATE DATABASE SHARED_DB FROM SHARE <provider_account>.SALES_ANALYTICS_SHARE;
-- SELECT * FROM SHARED_DB.ANALYTICS.SHARED_DAILY_SALES;
