-- ============================================================
-- Phase 1: Foundation — RBAC, Schemas, Warehouses
-- ============================================================

-- Database
CREATE DATABASE IF NOT EXISTS SALES_DW COMMENT = 'Sales Data Warehouse for pure Snowflake pipeline project';

-- Schemas
CREATE SCHEMA IF NOT EXISTS SALES_DW.RAW COMMENT = 'Raw ingested data - source of truth';
CREATE SCHEMA IF NOT EXISTS SALES_DW.STAGING COMMENT = 'Cleaned and transformed data';
CREATE SCHEMA IF NOT EXISTS SALES_DW.ANALYTICS COMMENT = 'Production marts - business-ready tables';
CREATE SCHEMA IF NOT EXISTS SALES_DW.DEV COMMENT = 'Developer sandbox for testing';

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS DEV_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Developer warehouse - ad hoc queries and testing';

CREATE WAREHOUSE IF NOT EXISTS REPORT_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Analyst warehouse - dashboards and reports';

CREATE WAREHOUSE IF NOT EXISTS PIPELINE_WH
  WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Pipeline warehouse - automated tasks and ingestion';

-- Roles
CREATE ROLE IF NOT EXISTS DEVELOPER COMMENT = 'Developer role - read/write DEV & RAW, read STAGING & ANALYTICS';
CREATE ROLE IF NOT EXISTS ANALYST COMMENT = 'Analyst role - read-only on ANALYTICS marts';
CREATE ROLE IF NOT EXISTS PIPELINE_ROLE COMMENT = 'Pipeline role - automated tasks, read/write RAW, STAGING, ANALYTICS';

-- Role hierarchy (grant to SYSADMIN)
GRANT ROLE DEVELOPER TO ROLE SYSADMIN;
GRANT ROLE ANALYST TO ROLE SYSADMIN;
GRANT ROLE PIPELINE_ROLE TO ROLE SYSADMIN;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEVELOPER;
GRANT USAGE ON WAREHOUSE REPORT_WH TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE PIPELINE_WH TO ROLE PIPELINE_ROLE;

-- Database grants
GRANT USAGE ON DATABASE SALES_DW TO ROLE DEVELOPER;
GRANT USAGE ON DATABASE SALES_DW TO ROLE ANALYST;
GRANT USAGE ON DATABASE SALES_DW TO ROLE PIPELINE_ROLE;

-- PIPELINE_ROLE: full access to RAW, STAGING, ANALYTICS
GRANT ALL ON SCHEMA SALES_DW.RAW TO ROLE PIPELINE_ROLE;
GRANT ALL ON SCHEMA SALES_DW.STAGING TO ROLE PIPELINE_ROLE;
GRANT ALL ON SCHEMA SALES_DW.ANALYTICS TO ROLE PIPELINE_ROLE;

-- DEVELOPER: full DEV & RAW, read STAGING & ANALYTICS
GRANT ALL ON SCHEMA SALES_DW.DEV TO ROLE DEVELOPER;
GRANT ALL ON SCHEMA SALES_DW.RAW TO ROLE DEVELOPER;
GRANT USAGE ON SCHEMA SALES_DW.STAGING TO ROLE DEVELOPER;
GRANT USAGE ON SCHEMA SALES_DW.ANALYTICS TO ROLE DEVELOPER;

-- ANALYST: read-only ANALYTICS
GRANT USAGE ON SCHEMA SALES_DW.ANALYTICS TO ROLE ANALYST;

-- Future grants
GRANT ALL ON FUTURE TABLES IN SCHEMA SALES_DW.RAW TO ROLE PIPELINE_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA SALES_DW.STAGING TO ROLE PIPELINE_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA SALES_DW.ANALYTICS TO ROLE PIPELINE_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA SALES_DW.DEV TO ROLE DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DW.STAGING TO ROLE DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DW.ANALYTICS TO ROLE DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DW.ANALYTICS TO ROLE ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SALES_DW.ANALYTICS TO ROLE ANALYST;
