-- ============================================================
-- Phase 4: Dynamic Tables — Auto-Refreshing Analytics Layer
-- ============================================================

CREATE OR REPLACE DYNAMIC TABLE SALES_DW.ANALYTICS.FCT_ORDERS
  TARGET_LAG = '5 minutes' WAREHOUSE = PIPELINE_WH
AS
SELECT
    o.ORDER_ID, o.CUSTOMER_ID, o.ORDER_DATE, o.STATUS, o.TOTAL_AMOUNT,
    COUNT(oi.ITEM_ID) AS LINE_ITEM_COUNT,
    SUM(oi.QUANTITY) AS TOTAL_QUANTITY,
    SUM(oi.LINE_TOTAL) AS COMPUTED_TOTAL,
    AVG(oi.UNIT_PRICE) AS AVG_UNIT_PRICE
FROM SALES_DW.STAGING.STG_ORDERS o
LEFT JOIN SALES_DW.STAGING.STG_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
GROUP BY o.ORDER_ID, o.CUSTOMER_ID, o.ORDER_DATE, o.STATUS, o.TOTAL_AMOUNT;

CREATE OR REPLACE DYNAMIC TABLE SALES_DW.ANALYTICS.DIM_CUSTOMERS
  TARGET_LAG = '5 minutes' WAREHOUSE = PIPELINE_WH
AS
SELECT
    c.CUSTOMER_ID, c.CUSTOMER_NAME, c.EMAIL, c.SEGMENT, c.COUNTRY, c.CREATED_AT,
    COUNT(o.ORDER_ID) AS TOTAL_ORDERS,
    COALESCE(SUM(o.TOTAL_AMOUNT), 0) AS LIFETIME_REVENUE,
    COALESCE(AVG(o.TOTAL_AMOUNT), 0) AS AVG_ORDER_VALUE,
    MIN(o.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE
FROM SALES_DW.STAGING.STG_CUSTOMERS c
LEFT JOIN SALES_DW.STAGING.STG_ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.EMAIL, c.SEGMENT, c.COUNTRY, c.CREATED_AT;

CREATE OR REPLACE DYNAMIC TABLE SALES_DW.ANALYTICS.DIM_PRODUCTS
  TARGET_LAG = '5 minutes' WAREHOUSE = PIPELINE_WH
AS
SELECT
    p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, p.BRAND, p.PRICE, p.CREATED_AT,
    COUNT(DISTINCT oi.ORDER_ID) AS TOTAL_ORDERS,
    COALESCE(SUM(oi.QUANTITY), 0) AS TOTAL_QUANTITY_SOLD,
    COALESCE(SUM(oi.LINE_TOTAL), 0) AS TOTAL_REVENUE
FROM SALES_DW.STAGING.STG_PRODUCTS p
LEFT JOIN SALES_DW.STAGING.STG_ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, p.BRAND, p.PRICE, p.CREATED_AT;

CREATE OR REPLACE DYNAMIC TABLE SALES_DW.ANALYTICS.DAILY_SALES_SUMMARY
  TARGET_LAG = '5 minutes' WAREHOUSE = PIPELINE_WH
AS
SELECT
    o.ORDER_DATE,
    COUNT(DISTINCT o.ORDER_ID) AS ORDER_COUNT,
    COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) AS DAILY_REVENUE,
    AVG(o.TOTAL_AMOUNT) AS AVG_ORDER_VALUE,
    SUM(oi.QUANTITY) AS TOTAL_ITEMS_SOLD
FROM SALES_DW.STAGING.STG_ORDERS o
LEFT JOIN SALES_DW.STAGING.STG_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
GROUP BY o.ORDER_DATE;
