-- ============================================================
-- Phase 3: Streams & Tasks — CDC Pipeline (RAW → STAGING)
-- ============================================================

-- Staging Tables
CREATE OR REPLACE TABLE SALES_DW.STAGING.STG_CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY, CUSTOMER_NAME VARCHAR, EMAIL VARCHAR,
    SEGMENT VARCHAR, COUNTRY VARCHAR, CREATED_AT DATE,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SALES_DW.STAGING.STG_ORDERS (
    ORDER_ID NUMBER PRIMARY KEY, CUSTOMER_ID NUMBER, ORDER_DATE DATE,
    STATUS VARCHAR, TOTAL_AMOUNT NUMBER(12,2),
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SALES_DW.STAGING.STG_PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY, PRODUCT_NAME VARCHAR, CATEGORY VARCHAR,
    BRAND VARCHAR, PRICE NUMBER(10,2), CREATED_AT DATE,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SALES_DW.STAGING.STG_ORDER_ITEMS (
    ITEM_ID NUMBER PRIMARY KEY, ORDER_ID NUMBER, PRODUCT_ID NUMBER,
    QUANTITY NUMBER, UNIT_PRICE NUMBER(10,2), LINE_TOTAL NUMBER(12,2),
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Streams (CDC on raw tables)
CREATE OR REPLACE STREAM SALES_DW.RAW.CUSTOMERS_STREAM ON TABLE SALES_DW.RAW.RAW_CUSTOMERS SHOW_INITIAL_ROWS = TRUE;
CREATE OR REPLACE STREAM SALES_DW.RAW.ORDERS_STREAM ON TABLE SALES_DW.RAW.RAW_ORDERS SHOW_INITIAL_ROWS = TRUE;
CREATE OR REPLACE STREAM SALES_DW.RAW.PRODUCTS_STREAM ON TABLE SALES_DW.RAW.RAW_PRODUCTS SHOW_INITIAL_ROWS = TRUE;
CREATE OR REPLACE STREAM SALES_DW.RAW.ORDER_ITEMS_STREAM ON TABLE SALES_DW.RAW.RAW_ORDER_ITEMS SHOW_INITIAL_ROWS = TRUE;

-- Tasks (auto-process stream → staging)
CREATE OR REPLACE TASK SALES_DW.RAW.PROCESS_CUSTOMERS
  WAREHOUSE = PIPELINE_WH SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('SALES_DW.RAW.CUSTOMERS_STREAM')
AS
  MERGE INTO SALES_DW.STAGING.STG_CUSTOMERS tgt
  USING (
    SELECT CUSTOMER_ID, UPPER(TRIM(CUSTOMER_NAME)) AS CUSTOMER_NAME,
           LOWER(TRIM(EMAIL)) AS EMAIL, UPPER(TRIM(SEGMENT)) AS SEGMENT,
           UPPER(TRIM(COUNTRY)) AS COUNTRY, CREATED_AT,
           METADATA$ACTION, METADATA$ISUPDATE
    FROM SALES_DW.RAW.CUSTOMERS_STREAM
  ) src ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
  WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN DELETE
  WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE
    THEN UPDATE SET tgt.CUSTOMER_NAME = src.CUSTOMER_NAME, tgt.EMAIL = src.EMAIL,
                    tgt.SEGMENT = src.SEGMENT, tgt.COUNTRY = src.COUNTRY,
                    tgt.CREATED_AT = src.CREATED_AT, tgt.LOADED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT'
    THEN INSERT VALUES (src.CUSTOMER_ID, src.CUSTOMER_NAME, src.EMAIL, src.SEGMENT, src.COUNTRY, src.CREATED_AT, CURRENT_TIMESTAMP());

CREATE OR REPLACE TASK SALES_DW.RAW.PROCESS_ORDERS
  WAREHOUSE = PIPELINE_WH SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('SALES_DW.RAW.ORDERS_STREAM')
AS
  MERGE INTO SALES_DW.STAGING.STG_ORDERS tgt
  USING (
    SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, UPPER(TRIM(STATUS)) AS STATUS,
           TOTAL_AMOUNT, METADATA$ACTION, METADATA$ISUPDATE
    FROM SALES_DW.RAW.ORDERS_STREAM
  ) src ON tgt.ORDER_ID = src.ORDER_ID
  WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN DELETE
  WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE
    THEN UPDATE SET tgt.CUSTOMER_ID = src.CUSTOMER_ID, tgt.ORDER_DATE = src.ORDER_DATE,
                    tgt.STATUS = src.STATUS, tgt.TOTAL_AMOUNT = src.TOTAL_AMOUNT, tgt.LOADED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT'
    THEN INSERT VALUES (src.ORDER_ID, src.CUSTOMER_ID, src.ORDER_DATE, src.STATUS, src.TOTAL_AMOUNT, CURRENT_TIMESTAMP());

CREATE OR REPLACE TASK SALES_DW.RAW.PROCESS_PRODUCTS
  WAREHOUSE = PIPELINE_WH SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('SALES_DW.RAW.PRODUCTS_STREAM')
AS
  MERGE INTO SALES_DW.STAGING.STG_PRODUCTS tgt
  USING (
    SELECT PRODUCT_ID, TRIM(PRODUCT_NAME) AS PRODUCT_NAME, UPPER(TRIM(CATEGORY)) AS CATEGORY,
           UPPER(TRIM(BRAND)) AS BRAND, PRICE, CREATED_AT, METADATA$ACTION, METADATA$ISUPDATE
    FROM SALES_DW.RAW.PRODUCTS_STREAM
  ) src ON tgt.PRODUCT_ID = src.PRODUCT_ID
  WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN DELETE
  WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE
    THEN UPDATE SET tgt.PRODUCT_NAME = src.PRODUCT_NAME, tgt.CATEGORY = src.CATEGORY,
                    tgt.BRAND = src.BRAND, tgt.PRICE = src.PRICE, tgt.CREATED_AT = src.CREATED_AT, tgt.LOADED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT'
    THEN INSERT VALUES (src.PRODUCT_ID, src.PRODUCT_NAME, src.CATEGORY, src.BRAND, src.PRICE, src.CREATED_AT, CURRENT_TIMESTAMP());

CREATE OR REPLACE TASK SALES_DW.RAW.PROCESS_ORDER_ITEMS
  WAREHOUSE = PIPELINE_WH SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('SALES_DW.RAW.ORDER_ITEMS_STREAM')
AS
  MERGE INTO SALES_DW.STAGING.STG_ORDER_ITEMS tgt
  USING (
    SELECT ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE,
           QUANTITY * UNIT_PRICE AS LINE_TOTAL, METADATA$ACTION, METADATA$ISUPDATE
    FROM SALES_DW.RAW.ORDER_ITEMS_STREAM
  ) src ON tgt.ITEM_ID = src.ITEM_ID
  WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN DELETE
  WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE
    THEN UPDATE SET tgt.ORDER_ID = src.ORDER_ID, tgt.PRODUCT_ID = src.PRODUCT_ID,
                    tgt.QUANTITY = src.QUANTITY, tgt.UNIT_PRICE = src.UNIT_PRICE,
                    tgt.LINE_TOTAL = src.LINE_TOTAL, tgt.LOADED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT'
    THEN INSERT VALUES (src.ITEM_ID, src.ORDER_ID, src.PRODUCT_ID, src.QUANTITY, src.UNIT_PRICE, src.LINE_TOTAL, CURRENT_TIMESTAMP());

-- Resume all tasks
ALTER TASK SALES_DW.RAW.PROCESS_CUSTOMERS RESUME;
ALTER TASK SALES_DW.RAW.PROCESS_ORDERS RESUME;
ALTER TASK SALES_DW.RAW.PROCESS_PRODUCTS RESUME;
ALTER TASK SALES_DW.RAW.PROCESS_ORDER_ITEMS RESUME;
